### ISSUE TITLE
I am unable to build. I get the following message when trying to build:

### ISSUE THREAD

**Issue by sorryimchad** [TTExtensions/MouseClickSimulator#7]
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets
(723,5): error : The OutputPath property is not set for project 'TTMouseclickSimulator.csproj'.
Please check to make sure that you have specified a valid combination of Configuration and Platform for this project. Configuration= 'Release'  Platform= 'MCD'. You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project.  [C:\Users\Devin\Downloads\MouseClickSimulator-master\TTMouseclickSimulator\TTMouseclicksimulator.csproj]

I downloaded all the necessary programs in the wiki, and i have winrar for zipping, but otherwise I really DONT know what I'm doing programming-wise.

**Comment by TTExtensions** [comment]
Thanks. The problem was that MSBuild fills parameters that aren't specified on the command line from environment variables, so if a system hat set a "Platform" env variable, the build would fail.
I have fixed the problem in the BUILD.cmd file.

Please re-download the current version as ZIP file, and check if the build is working now.
